# Generated by Django 4.1.5 on 2023-01-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poc', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=10)),
                ('level_2023', models.CharField(max_length=100)),
                ('subject1', models.CharField(max_length=100)),
                ('subject2', models.CharField(max_length=100)),
                ('subject3', models.CharField(max_length=100)),
                ('financial_aid', models.CharField(max_length=5)),
                ('available', models.CharField(max_length=5)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=2)),
                ('level', models.CharField(max_length=5)),
                ('subject1', models.CharField(max_length=100)),
                ('subject2', models.CharField(max_length=100)),
                ('probono', models.CharField(max_length=2)),
                ('available', models.CharField(max_length=2)),
            ],
        ),
    ]
